### PR TITLE
Housing price plot

### LINKED ISSUE #46: Find plotting method for the housing price indicator

### PR DESCRIPTION
**Pull request by Augustin4762**
Changed the sidebar frame.
Added the plot for the housing price indicator (only per municipalities).

### CODE REVIEW

**Review by ikbentimkramer — COMMENTED** [review]
It does not run, because `get_data()` does not understand the string `housing_price`. Is this intentional?

**Comment by Augustin4762** [comment]
> It does not run, because `get_data()` does not understand the string `housing_price`. Is this intentional?
Might be because of the pr #50, as that part introduces the housing_price into the getdata. As I remember when I started working on this pr, I pulled dev and I should have been working on the latest version of dev, which was including the housing_price in get_data, but maybe I messed smthing up and it was only locally

Edit: Yeah, I worked on my branch that already had the previous pr #50

**Comment by ikbentimkramer** [comment]
Merged dev (which contains #50 now) with this branch. It runs now. If the CI completes without hitches, this can be merged.

**Review by ikbentimkramer — APPROVED** [review]
Looks good to me!

**Pull request merged**
