### PR TITLE
Implement map

### LINKED ISSUE #65: Implement map for housing prices

### PR DESCRIPTION
**Pull request by Augustin4762**
Creates a map for the housing price indicator
Adjusts the scale and changes colours on the previous housing stock map

### CODE REVIEW

**Comment by Augustin4762** [comment]
Again got conflicting files, because dev is now different from the one I started with. Tried to commit the new files while keeping the latest dev changes as well, but the conflict is still there. Also this pr is trying to run the travis check, shall I create a new pr so it will switch to the new tests?

**Comment by ikbentimkramer** [comment]
Not necessary to start a new PR. Resolving the merge conflicts also resolved the CI issue

**Comment by Augustin4762** [comment]
Brilliant, thanks, please take a look at the maps and tell me if they are good in this state. Otherwise, I could come up with small improvements.

**Review by ikbentimkramer — CHANGES_REQUESTED** [review]
Please add tests for `price_map_server`

**Comment by ikbentimkramer** [comment]
I fixed the `municip_code` bug. For some arcane reason the `df[["Gemeentecode"]] <- NULL` line was removing `municip_code` *after* the column `GemeentecodeGM` (a different column!!) was renamed to `municip_code`.

**Review by ikbentimkramer — APPROVED** [review]

**Pull request merged**
