### PR TITLE
Implementing the migration map

### LINKED ISSUE #64: Implement map for migration data

### LINKED ISSUE #92: Province and municipality are swapped in migration data

### PR DESCRIPTION
**Pull request by Augustin4762**
-Modules for the migration map added
-Data is used from the imputed dataset, needed a new filtering function
-fixes issue #92

### CODE REVIEW

**Comment by Augustin4762** [comment]
Can't figure out how to fix the error.

**Comment by ikbentimkramer** [comment]
The reason codecov does not pass is because there are no tests for `migration_map_server` or `filter_imputed_migration_data`

**Comment by Augustin4762** [comment]
Alright, I will write the tests and then add the boxplot

**Review by ikbentimkramer — APPROVED** [review]
Looks good to me!

**Pull request merged**
